// Makora — datos de catálogo
// Solo técnicas propias: Sublimación, Vinil, Vinil textil / DTF, Impresión 3D
// Otras técnicas (resina, bordado, láser, serigrafía) están en roadmap futuro.

window.MAKORA_CATEGORIES = [
  { id: "sublimacion", name: "Sublimación", short: "Sublim.", desc: "Tazas, termos, mousepads y más con impresión a todo color.", accent: "#0F9787", heroImg: "https://images.unsplash.com/photo-1572119003128-d110c07af847?w=900&auto=format&fit=crop&q=80" },
  { id: "textil",      name: "Textil personalizado", short: "Textil", desc: "Camisetas, hoodies y uniformes en vinil textil y DTF imprimible.", accent: "#13224A", heroImg: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&auto=format&fit=crop&q=80" },
  { id: "3d",          name: "Impresión 3D", short: "3D", desc: "Llaveros, figuras, organizadores y prototipos funcionales.", accent: "#C8853D", heroImg: "https://images.unsplash.com/photo-1612886623691-bea1568eb6e2?w=900&auto=format&fit=crop&q=80" },
  { id: "corporativo", name: "Corporativo", short: "Corporativo", desc: "Kits, regalos y branding para empresas y eventos.", accent: "#13224A", heroImg: "https://images.unsplash.com/photo-1611224885990-ab7363d1f2a9?w=900&auto=format&fit=crop&q=80" },
  { id: "temporadas",  name: "Temporadas", short: "Temporadas", desc: "Detalles para Navidad, Día del Padre, regreso a clases y más.", accent: "#0F9787", heroImg: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=900&auto=format&fit=crop&q=80" },
  { id: "packaging",   name: "Packaging y complementos", short: "Packaging", desc: "Cajas, etiquetas, tarjetas e inserts para que el regalo sume.", accent: "#C8853D", heroImg: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=900&auto=format&fit=crop&q=80" },
];

const T = (label, sub) => ({ label, sub });
const U = (id, w = 800) => `https://images.unsplash.com/photo-${id}?w=${w}&auto=format&fit=crop&q=80`;

window.MAKORA_PRODUCTS = [
  // === SUBLIMACIÓN ===
  { id: "s01", cat: "sublimacion", name: "Taza cerámica 11oz", technique: "Sublimación", material: "Cerámica blanca AAA", colors: ["Blanco", "Mate", "Mágica"], lead: "3–5 días", min: 1, priceFrom: 7.5, tags: ["Regalo", "Personal", "Bestseller"], state: "popular", img: U("1572119003128-d110c07af847"), placeholder: T("TAZA 11oz", "Sublimación full color") },
  { id: "s02", cat: "sublimacion", name: "Termo acero 20oz", technique: "Sublimación", material: "Acero inoxidable", colors: ["Blanco", "Plateado"], lead: "5–7 días", min: 1, priceFrom: 18, tags: ["Regalo", "Corporativo"], state: "destacado", img: U("1602143407151-7111542de6e8"), placeholder: T("TERMO 20oz", "Acero sublimable") },
  { id: "s03", cat: "sublimacion", name: "Cojín 40×40cm", technique: "Sublimación", material: "Poliéster", colors: ["Blanco"], lead: "5–7 días", min: 1, priceFrom: 14, tags: ["Regalo", "Hogar"], state: "nuevo", img: U("1592078615290-033ee584e267"), placeholder: T("COJÍN 40×40", "Sublimación a una cara") },
  { id: "s04", cat: "sublimacion", name: "Mousepad personalizado", technique: "Sublimación", material: "Tela + caucho", colors: ["Full color"], lead: "3–4 días", min: 1, priceFrom: 9, tags: ["Personal", "Oficina"], state: "popular", img: U("1629429407759-94bce53a3a6f"), placeholder: T("MOUSEPAD", "22×18cm") },
  { id: "s05", cat: "sublimacion", name: "Rompecabezas A4", technique: "Sublimación", material: "MDF + papel", colors: ["Full color"], lead: "5–7 días", min: 1, priceFrom: 12, tags: ["Regalo", "Niños"], state: null, img: U("1606326608606-aa0b62935f2b"), placeholder: T("PUZZLE A4", "120 piezas") },
  { id: "s06", cat: "sublimacion", name: "Placa MDF brillante", technique: "Sublimación", material: "MDF sublimable", colors: ["Blanco brillante"], lead: "4–6 días", min: 1, priceFrom: 11, tags: ["Decoración", "Regalo"], state: null, img: U("1581783898377-1c85bf937427"), placeholder: T("PLACA MDF", "20×30cm") },
  { id: "s07", cat: "sublimacion", name: "Llavero sublimable", technique: "Sublimación", material: "MDF / metal", colors: ["Plata", "Madera"], lead: "3–5 días", min: 5, priceFrom: 2.5, tags: ["Souvenir", "Evento"], state: null, img: U("1622560480605-d83c853bc5c3"), placeholder: T("LLAVERO", "Pack desde 5u") },
  { id: "s08", cat: "sublimacion", name: "Taza mágica térmica", technique: "Sublimación", material: "Cerámica negra", colors: ["Negro mágico"], lead: "4–6 días", min: 1, priceFrom: 12, tags: ["Regalo", "Sorpresa"], state: "destacado", img: U("1514228742587-6b1558fcca3d"), placeholder: T("MUG MÁGICA", "Cambio térmico") },
  { id: "s09", cat: "sublimacion", name: "Pin botón 58mm", technique: "Sublimación", material: "Hojalata", colors: ["Full color"], lead: "3–5 días", min: 10, priceFrom: 1.2, tags: ["Evento", "Souvenir"], state: null, img: U("1635405074683-96d6921a2a68"), placeholder: T("PIN 58mm", "Mín. 10 unidades") },
  { id: "s10", cat: "sublimacion", name: "Funda celular flexible", technique: "Sublimación", material: "TPU sublimable", colors: ["Mate", "Brillo"], lead: "5–8 días", min: 1, priceFrom: 16, tags: ["Personal", "Regalo"], state: "nuevo", img: U("1601593346740-925612772716"), placeholder: T("FUNDA", "iPhone / Samsung") },

  // === TEXTIL ===
  { id: "t01", cat: "textil", name: "Camiseta unisex algodón", technique: "Vinil textil / DTF", material: "Algodón 180g", colors: ["Blanco", "Negro", "Crema", "Verde"], lead: "5–7 días", min: 1, priceFrom: 11, tags: ["Personal", "Evento"], state: "bestseller", img: U("1521572163474-6864f9cf17ab"), placeholder: T("T-SHIRT", "Algodón 180g") },
  { id: "t02", cat: "textil", name: "Hoodie premium", technique: "DTF", material: "French terry 320g", colors: ["Negro", "Crema", "Marino"], lead: "7–10 días", min: 1, priceFrom: 38, tags: ["Personal", "Regalo"], state: "destacado", img: U("1556821840-3a63f95609a7"), placeholder: T("HOODIE", "French terry") },
  { id: "t03", cat: "textil", name: "Suéter cuello redondo", technique: "DTF", material: "Mezcla 50/50", colors: ["Gris", "Negro", "Crema"], lead: "7–10 días", min: 1, priceFrom: 28, tags: ["Personal"], state: null, img: U("1620799140408-edc6dcb6d633"), placeholder: T("SUÉTER", "Crewneck") },
  { id: "t04", cat: "textil", name: "Polo uniforme corporativo", technique: "Vinil textil / DTF", material: "Piqué 200g", colors: ["6 colores"], lead: "8–12 días", min: 6, priceFrom: 16, tags: ["Corporativo", "Empresas"], state: "popular", img: U("1586790170083-2f9ceadc732d"), placeholder: T("POLO", "Piqué 200g") },
  { id: "t05", cat: "textil", name: "Bolsa de tela tote", technique: "Vinil textil / DTF", material: "Algodón 100% 8oz", colors: ["Crudo", "Negro"], lead: "5–7 días", min: 1, priceFrom: 6.5, tags: ["Evento", "Promocional"], state: null, img: U("1591561954557-26941169b49e"), placeholder: T("TOTE BAG", "Algodón crudo") },
  { id: "t06", cat: "textil", name: "Gorra trucker DTF", technique: "DTF", material: "Algodón + mesh", colors: ["Negro", "Marino", "Beige"], lead: "7–10 días", min: 1, priceFrom: 14, tags: ["Personal", "Promocional"], state: null, img: U("1521369909029-2afed882baee"), placeholder: T("GORRA", "Trucker") },
  { id: "t07", cat: "textil", name: "Camiseta deportiva drifit", technique: "Sublimación textil", material: "Poliéster perforado", colors: ["Sublimación full color"], lead: "5–8 días", min: 1, priceFrom: 13, tags: ["Deporte", "Equipos"], state: "nuevo", img: U("1517438476312-10d79c077509"), placeholder: T("DRIFIT", "Sublimable") },
  { id: "t08", cat: "textil", name: "Delantal personalizado", technique: "Vinil textil / DTF", material: "Lona + canvas", colors: ["Negro", "Crudo", "Marino"], lead: "5–7 días", min: 1, priceFrom: 15, tags: ["Regalo", "Restaurante"], state: null, img: U("1581349485608-9469926a8e5e"), placeholder: T("DELANTAL", "Canvas") },
  { id: "t09", cat: "textil", name: "Body bebé DTF", technique: "DTF", material: "Algodón suave", colors: ["Blanco", "Rosa", "Celeste"], lead: "4–6 días", min: 1, priceFrom: 9, tags: ["Regalo", "Baby shower"], state: "popular", img: U("1522771930-78848d9293e8"), placeholder: T("BODY BEBÉ", "0–24m") },
  { id: "t10", cat: "textil", name: "Set uniforme deportivo", technique: "Sublimación textil", material: "Microfibra", colors: ["Diseño completo"], lead: "10–15 días", min: 8, priceFrom: 24, tags: ["Equipos", "Empresas"], state: null, img: U("1517466787929-bc90951d0974"), placeholder: T("UNIFORME", "Set completo") },

  // === IMPRESIÓN 3D ===
  { id: "d01", cat: "3d", name: "Llavero 3D personalizado", technique: "Impresión 3D FDM", material: "PLA", colors: ["12+ colores"], lead: "3–5 días", min: 1, priceFrom: 3, tags: ["Souvenir", "Personal"], state: "popular", img: U("1631544114551-99c4b40f5b79"), placeholder: T("LLAVERO 3D", "PLA mate") },
  { id: "d02", cat: "3d", name: "Figura coleccionable FDM", technique: "Impresión 3D FDM", material: "PLA", colors: ["Multi"], lead: "5–8 días", min: 1, priceFrom: 18, tags: ["Coleccionista", "Regalo"], state: "destacado", img: U("1612886623691-bea1568eb6e2"), placeholder: T("FIGURA 3D", "PLA") },
  { id: "d03", cat: "3d", name: "Organizador de escritorio", technique: "Impresión 3D FDM", material: "PLA / PETG", colors: ["Negro", "Blanco", "Madera"], lead: "5–7 días", min: 1, priceFrom: 18, tags: ["Oficina", "Hogar"], state: null, img: U("1611532736597-de2d4265fba3"), placeholder: T("ORGANIZADOR", "Modular") },
  { id: "d04", cat: "3d", name: "Rótulo / letrero corpóreo", technique: "Impresión 3D", material: "PLA + acabado", colors: ["A elección"], lead: "7–12 días", min: 1, priceFrom: 35, tags: ["Negocio", "Decoración"], state: null, img: U("1635405446898-a4c1ccaf91d4"), placeholder: T("RÓTULO 3D", "Letrero corpóreo") },
  { id: "d05", cat: "3d", name: "Pieza funcional a medida", technique: "Impresión 3D", material: "PETG / ABS", colors: ["Funcional"], lead: "Cotización", min: 1, priceFrom: null, tags: ["Repuesto", "Industrial"], state: null, img: U("1581092160562-40aa08e78837"), placeholder: T("PIEZA TÉCNICA", "Bajo plano") },
  { id: "d06", cat: "3d", name: "Topper para torta", technique: "Impresión 3D", material: "PLA seguro", colors: ["A elección"], lead: "3–5 días", min: 1, priceFrom: 6, tags: ["Cumpleaños", "Evento"], state: "popular", img: U("1535141192574-5d4897c12636"), placeholder: T("CAKE TOPPER", "PLA") },
  { id: "d07", cat: "3d", name: "Maceta geométrica", technique: "Impresión 3D", material: "PLA matte", colors: ["Terracota", "Blanco", "Negro"], lead: "5–7 días", min: 1, priceFrom: 12, tags: ["Hogar", "Regalo"], state: null, img: U("1485955900006-10f4d324d411"), placeholder: T("MACETA", "Geométrica") },
  { id: "d08", cat: "3d", name: "Soporte para auriculares", technique: "Impresión 3D", material: "PLA", colors: ["Multi"], lead: "3–5 días", min: 1, priceFrom: 14, tags: ["Oficina", "Personal"], state: "nuevo", img: U("1583394838336-acd977736f90"), placeholder: T("HEADPHONE STAND", "PLA") },
  { id: "d09", cat: "3d", name: "Soporte para celular", technique: "Impresión 3D", material: "PLA", colors: ["Multi"], lead: "3–4 días", min: 1, priceFrom: 8, tags: ["Oficina", "Personal"], state: null, img: U("1592890288564-76628a30a657"), placeholder: T("STAND CELU", "PLA matte") },
  { id: "d10", cat: "3d", name: "Prototipo a escala", technique: "Impresión 3D", material: "PETG", colors: ["Funcional"], lead: "Cotización", min: 1, priceFrom: null, tags: ["Diseño", "Empresas"], state: null, img: U("1567361808960-dec9cb578182"), placeholder: T("PROTOTIPO", "Bajo CAD") },

  // === CORPORATIVO ===
  { id: "c01", cat: "corporativo", name: "Taza con logo empresa", technique: "Sublimación", material: "Cerámica", colors: ["Blanco", "Color"], lead: "5–8 días", min: 12, priceFrom: 6.5, tags: ["Empresas", "Volumen"], state: "destacado", img: U("1577937927133-66ef06acdf18"), placeholder: T("TAZA LOGO", "Volumen ≥12u") },
  { id: "c02", cat: "corporativo", name: "Termo corporativo", technique: "Vinil", material: "Acero inoxidable", colors: ["Negro", "Plateado", "Blanco"], lead: "8–12 días", min: 10, priceFrom: 16, tags: ["Empresas", "Eventos"], state: null, img: U("1610824352934-c10d87b700cc"), placeholder: T("TERMO LOGO", "Acero") },
  { id: "c03", cat: "corporativo", name: "Kit promocional 4 piezas", technique: "Mixta (Sublim. + Vinil + 3D)", material: "Variado", colors: ["Branding"], lead: "10–15 días", min: 20, priceFrom: 22, tags: ["Empresas", "Eventos"], state: "popular", img: U("1611224885990-ab7363d1f2a9"), placeholder: T("KIT 4 PIEZAS", "Taza + tote + llavero + libreta") },
  { id: "c04", cat: "corporativo", name: "Gift box ejecutiva", technique: "Mixta", material: "Caja rígida + productos", colors: ["Branding"], lead: "12–18 días", min: 10, priceFrom: 38, tags: ["Empresas", "Regalo VIP"], state: "nuevo", img: U("1549465220-1a8b9238cd48"), placeholder: T("GIFT BOX", "Premium") },
  { id: "c05", cat: "corporativo", name: "Identificador / lanyard", technique: "Sublimación", material: "Poliéster + clip", colors: ["Branding"], lead: "5–8 días", min: 25, priceFrom: 2.2, tags: ["Eventos", "Empresas"], state: null, img: U("1582719188393-bb71ca45dbb9"), placeholder: T("LANYARD", "Sublimado") },
  { id: "c06", cat: "corporativo", name: "Libreta personalizada", technique: "Vinil", material: "Cuero sintético", colors: ["Negro", "Marino", "Marrón"], lead: "8–12 días", min: 10, priceFrom: 9, tags: ["Empresas", "Conferencia"], state: null, img: U("1531346878377-a5be20888e57"), placeholder: T("LIBRETA", "A5 cuero") },
  { id: "c07", cat: "corporativo", name: "Mousepad branding", technique: "Sublimación", material: "Tela", colors: ["Full color"], lead: "5–8 días", min: 20, priceFrom: 6, tags: ["Empresas", "Oficina"], state: null, img: U("1593642632559-0c6d3fc62b89"), placeholder: T("MOUSEPAD CORP", "Branding") },
  { id: "c08", cat: "corporativo", name: "Bolsa eco corporativa", technique: "Vinil textil / DTF", material: "Algodón", colors: ["Crudo", "Negro"], lead: "7–10 días", min: 25, priceFrom: 5.5, tags: ["Empresas", "ESG"], state: null, img: U("1591348278863-a8fb3887e2aa"), placeholder: T("ECO BAG", "Algodón") },
  { id: "c09", cat: "corporativo", name: "Placa reconocimiento", technique: "Sublimación", material: "MDF + base", colors: ["Madera / blanco"], lead: "8–12 días", min: 1, priceFrom: 22, tags: ["Empresas", "Premio"], state: "destacado", img: U("1607344645866-009c320b63e0"), placeholder: T("RECONOCIM.", "Placa MDF") },
  { id: "c10", cat: "corporativo", name: "Set escritorio personalizado", technique: "Mixta (Vinil + 3D)", material: "Madera + 3D", colors: ["Branding"], lead: "10–14 días", min: 5, priceFrom: 28, tags: ["Empresas", "VIP"], state: "nuevo", img: U("1593642634402-b0eb5e2eebc9"), placeholder: T("SET DESK", "Madera + 3D") },

  // === TEMPORADAS ===
  { id: "h01", cat: "temporadas", name: "Caja navideña personalizada", technique: "Mixta", material: "Caja + productos", colors: ["Estacional"], lead: "10–14 días", min: 5, priceFrom: 24, tags: ["Navidad", "Empresas"], state: "destacado", img: U("1607344645866-009c320b63e0"), placeholder: T("BOX NAVIDAD", "Mix premium") },
  { id: "h02", cat: "temporadas", name: "Kit escolar personalizado", technique: "Vinil / Sublimación", material: "Mixto", colors: ["Niño / niña"], lead: "5–8 días", min: 1, priceFrom: 18, tags: ["Regreso a clases", "Niños"], state: "popular", img: U("1503676260728-1c00da094a0b"), placeholder: T("KIT ESCOLAR", "Mochila + lonchera") },
  { id: "h03", cat: "temporadas", name: "Detalle Día del Padre", technique: "Mixta", material: "Variado", colors: ["Estacional"], lead: "5–7 días", min: 1, priceFrom: 16, tags: ["Día del Padre", "Regalo"], state: "nuevo", img: U("1622445275576-721325763afe"), placeholder: T("PAPÁ", "Set 3 piezas") },
  { id: "h04", cat: "temporadas", name: "Box cumpleaños custom", technique: "Mixta", material: "Caja + impresión", colors: ["Custom"], lead: "7–10 días", min: 1, priceFrom: 22, tags: ["Cumpleaños", "Regalo"], state: "popular", img: U("1513885535751-8b9238bd345a"), placeholder: T("CUMPLE BOX", "Personalizable") },
  { id: "h05", cat: "temporadas", name: "Detalle San Valentín", technique: "Sublimación", material: "Mixto", colors: ["Rojo", "Pastel"], lead: "5–7 días", min: 1, priceFrom: 14, tags: ["San Valentín", "Pareja"], state: null, img: U("1518895949257-7621c3c786d7"), placeholder: T("VALENTÍN", "Taza + cojín") },
  { id: "h06", cat: "temporadas", name: "Souvenir para evento", technique: "Sublimación / Vinil", material: "Variado", colors: ["Branding evento"], lead: "10–14 días", min: 20, priceFrom: 3.5, tags: ["Eventos", "Souvenir"], state: null, img: U("1519671482749-fd09be7ccebf"), placeholder: T("SOUVENIR", "Mín. 20u") },
  { id: "h07", cat: "temporadas", name: "Adornos navideños 3D", technique: "Impresión 3D", material: "PLA", colors: ["Multi"], lead: "5–8 días", min: 1, priceFrom: 4.5, tags: ["Navidad", "Decoración"], state: "nuevo", img: U("1543589077-47d81606c1bf"), placeholder: T("ADORNO 3D", "Árbol / Reno") },
  { id: "h08", cat: "temporadas", name: "Detalle Día de la Madre", technique: "Sublimación", material: "Mixto", colors: ["Pastel"], lead: "5–7 días", min: 1, priceFrom: 14, tags: ["Día de la Madre", "Regalo"], state: null, img: U("1520006403909-838d6b92c22e"), placeholder: T("MAMÁ", "Taza + cojín") },
  { id: "h09", cat: "temporadas", name: "Kit graduación", technique: "Mixta", material: "Variado", colors: ["Custom"], lead: "8–12 días", min: 1, priceFrom: 26, tags: ["Graduación", "Evento"], state: null, img: U("1523050854058-8df90110c9f1"), placeholder: T("KIT GRAD", "Marco + taza") },
  { id: "h10", cat: "temporadas", name: "Calendario personalizado", technique: "Sublimación", material: "MDF", colors: ["Full color"], lead: "5–8 días", min: 1, priceFrom: 12, tags: ["Año nuevo", "Empresas"], state: null, img: U("1506784983877-45594efa4cbe"), placeholder: T("CALENDARIO", "Sobremesa") },

  // === PACKAGING ===
  { id: "p01", cat: "packaging", name: "Caja kraft personalizada", technique: "Vinil / Impresión", material: "Cartón kraft", colors: ["Kraft natural"], lead: "5–7 días", min: 10, priceFrom: 2.5, tags: ["E-commerce", "Regalo"], state: "popular", img: U("1607344645866-009c320b63e0"), placeholder: T("CAJA KRAFT", "Mín. 10u") },
  { id: "p02", cat: "packaging", name: "Etiqueta adhesiva troquelada", technique: "Impresión + corte", material: "Vinil mate / brillo", colors: ["Full color"], lead: "3–5 días", min: 25, priceFrom: 0.4, tags: ["Marca", "Producto"], state: null, img: U("1633409361618-c73427e4e206"), placeholder: T("STICKER", "Troquelado") },
  { id: "p03", cat: "packaging", name: "Tarjeta de agradecimiento", technique: "Impresión premium", material: "Cartulina 350g", colors: ["Mate / brillo"], lead: "3–5 días", min: 25, priceFrom: 0.6, tags: ["E-commerce", "Marca"], state: null, img: U("1606293459338-19b22f2dd25e"), placeholder: T("TARJETA THX", "350g") },
  { id: "p04", cat: "packaging", name: "Inserts personalizados", technique: "Impresión digital", material: "Cartulina", colors: ["Full color"], lead: "3–5 días", min: 25, priceFrom: 0.5, tags: ["E-commerce", "Marca"], state: null, img: U("1611162616475-46b635cb6868"), placeholder: T("INSERT", "Tarjeta marca") },
  { id: "p05", cat: "packaging", name: "Bolsa kraft con asa", technique: "Vinil", material: "Kraft + algodón", colors: ["Kraft", "Negro"], lead: "5–8 días", min: 25, priceFrom: 1.5, tags: ["Retail", "Regalo"], state: "nuevo", img: U("1591105575633-922b8506f747"), placeholder: T("BOLSA KRAFT", "Con asa") },
  { id: "p06", cat: "packaging", name: "Empaque para taza", technique: "Impresión", material: "Cartón corrugado", colors: ["Custom"], lead: "5–7 días", min: 10, priceFrom: 1.2, tags: ["Regalo", "Marca"], state: null, img: U("1606293459338-19b22f2dd25e"), placeholder: T("BOX TAZA", "Custom") },
  { id: "p07", cat: "packaging", name: "Etiqueta colgante hangtag", technique: "Impresión + troquel", material: "Cartulina + cordón", colors: ["Full color"], lead: "5–8 días", min: 25, priceFrom: 0.8, tags: ["Marca", "Retail"], state: null, img: U("1583484963886-cfe2bff2945f"), placeholder: T("HANGTAG", "Cartulina") },
  { id: "p08", cat: "packaging", name: "Tarjeta de presentación", technique: "Impresión premium", material: "Cartulina 350g", colors: ["Mate / brillo"], lead: "3–5 días", min: 50, priceFrom: 0.3, tags: ["Marca", "Empresas"], state: null, img: U("1556761175-5973dc0f32e7"), placeholder: T("BUSINESS CARD", "350g") },
  { id: "p09", cat: "packaging", name: "Bolsa zip personalizada", technique: "Impresión", material: "PE / kraft", colors: ["Custom"], lead: "12–18 días", min: 100, priceFrom: 0.45, tags: ["Producto", "Volumen"], state: null, img: U("1607344645866-009c320b63e0"), placeholder: T("BOLSA ZIP", "Mín. 100u") },
  { id: "p10", cat: "packaging", name: "Display de mostrador", technique: "Vinil + corte", material: "Cartón / acrílico", colors: ["Custom"], lead: "8–12 días", min: 1, priceFrom: 35, tags: ["Retail", "Marca"], state: "destacado", img: U("1567113463300-102a7eb3cb26"), placeholder: T("DISPLAY", "Mostrador") },
];

// Filtros — solo técnicas que Makora maneja directamente
window.MAKORA_FILTERS = {
  techniques: ["Sublimación", "Vinil", "Vinil textil / DTF", "DTF", "Impresión 3D", "Sublimación textil"],
  occasions: ["Regalo", "Evento", "Cumpleaños", "Navidad", "Día del Padre", "Día de la Madre", "San Valentín", "Graduación", "Baby shower", "Regreso a clases", "Aniversario"],
  audiences: ["Personal", "Empresas", "Eventos", "Equipos"],
  materials: ["Cerámica", "Algodón", "Poliéster", "PLA", "PETG", "MDF", "Cartón", "Cuero sintético", "Kraft"],
  prices: [
    { id: "p1", label: "Hasta $10", max: 10 },
    { id: "p2", label: "$10–$25", min: 10, max: 25 },
    { id: "p3", label: "$25–$50", min: 25, max: 50 },
    { id: "p4", label: "$50+", min: 50 },
    { id: "pq", label: "Cotización", quoteOnly: true },
  ],
  leads: ["3–5 días", "5–8 días", "8–14 días", "14+ días", "Cotización"],
};
